from setuptools import setup, find_packages

setup(
    name="alg_pii_engine",
    version="1.0.0",
    description="Algerian RegTech PII Compliance Platform (Law 18-07)",
    author="Alg-PII Team",
    packages=find_packages(),
    install_requires=[
        "PyQt6>=6.10.1,<6.11",
        "transformers>=4.40.0",
        "tokenizers>=0.19.0",
        "regex>=2024.4.0",
        "cryptography>=42.0.0",
        "keyring>=25.0.0",
        "sqlcipher3-wheels>=0.5.7",
        "croniter>=3.0.0",
        "PyMuPDF>=1.23.0",
        "python-docx>=1.1.0",
        "openpyxl>=3.1.2",
        "reportlab>=4.1.0",
        "extract-msg>=0.48.0",
        "pytesseract>=0.3.10",
        "opencv-python-headless>=4.9.0",
        "pillow>=10.0.0",
        "arabic-reshaper>=3.0.0",
        "python-bidi>=0.4.2",
        "requests>=2.31.0",
        "pyqtgraph>=0.13.3",
        "PyJWT>=2.8.0",
        "qtawesome>=1.3.1",
        "bcrypt>=4.1.2",
        "pyinstaller>=6.21.0",
        "pyinstaller-hooks-contrib>=2026.6",
    ],
    entry_points={
        "console_scripts": [
            "alg-pii-engine=main:main",
        ],
    },
)
